<a href="https://colab.research.google.com/github/Mosaraf15/Python-Fundamentals-for-Machine-Learning/blob/main/07_Mathematical_operations_in_Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematical operations in Python: NumPy
**Md Mosaraf Hossain Khan**,

Chittagang, Bangladesh

#### Objectives:
1. Comparison between List and NumPy array
2. 1D and 2D NumPy array
3. Mathematical and Matrix operation in NumPy array
4. NumPy array slicing and filtering

#### **References:**

Instructor:
####**Md Shahidullah Kawsar**,
  Data Scientist, IDARE, Houston, TX, USA

  1.https://github.com/SKawsar/Python_Fundamentals_s2/blob/main/Lecture_7.ipynb

In [ ]:
import numpy as np


list_1 = [1,2,3,4,5,6,7,8,9]
list_2 = [1,-2,3,-4,5,-6,7,-8,9]

list_add = list_1 + list_2
print(list_add)

##not allow in list Type error

# list_sub = list_1 - list_2
# print(list_sub)

# list_mul = list_1 * list_2
# print(list_mul)

# list_sub = list_1 / list_2
# print(list_sub)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, -2, 3, -4, 5, -6, 7, -8, 9]


In [ ]:
set(list_1) - set(list_2)

{2, 4, 6, 8}

In [ ]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
arr_2 = np.array([1,-2,3,-4,5,-6,7,-8,9])

print(type(arr_1))
print(type(arr_2))
print(arr_2.dtype)




arr_add = np.add(arr_1, arr_2)
print(arr_add)
print(type(arr_add))

arr_sub = np.subtract(arr_1, arr_2)
print(arr_sub)


arr_mul = np.multiply(arr_1, arr_2)
print(arr_mul)


arr_div = np.divide(arr_1, arr_2)
print(arr_div)

arr_mod = np.mod(arr_1, arr_2)
print("remainder after dividing two arrays = ", arr_mod)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
[ 2  0  6  0 10  0 14  0 18]
<class 'numpy.ndarray'>
[ 0  4  0  8  0 12  0 16  0]
[  1  -4   9 -16  25 -36  49 -64  81]
[ 1. -1.  1. -1.  1. -1.  1. -1.  1.]
remainder after dividing two arrays =  [0 0 0 0 0 0 0 0 0]
